version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ".:/usr/data/express-mongo-starter"
      - "/usr/data/express-mongo-starter/node_modules"
  db:
    image: mongo
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
